### ISSUE TITLE
Delete the repository

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/urlreplacer#2]
Wir sollten das unnötige Repo so langsam mal löschen.

**Comment by skerbis** [comment]
Nein, es wird ersetzt. In Kürze.

**Comment by schuer** [comment]
Hey Joachim, mal zum Verständnis gefragt: Ist der Code irgendwie fehlerhaft oder überflüssig oder womöglich schädlich, so dass man ihn entfernen wollte? Wenn nicht, würde ich als Nutzer, der das AddOn irgendwo installiert hat, nämlich erwarten, dass ein Repo dauerhaft bestehen bleibt. Man würde das AddOn aus dem Installer nehmen, um es nicht weiter zu verbreiten, aber man würde eigentlich nicht das GitHub-Repo löschen. Denn das enthält die komplette Entwicklungshistorie, die Abstimmung über Features, die Issues, die getroffenen Entscheidungen, usw.

Ich hätte das Repo auch nicht leergeräumt, so wie es hier passiert ist, sondern hätte lediglich gut sichtbar darüber den Deprecated-Hinweis gepappt. Und damit es hilfreich für Nutzer ist, die das AddOn installiert haben, eine Info, welche Alternative sie nun stattdessen benutzen können/sollen.

Die Frage also: Gibt es ernste Gründe, das hier bewusst löschen zu wollen, oder geht es eigentlich nur darum, dass es nicht weiter gepflegt wird?

**Comment by skerbis** [comment]
@schuer Vorschlag: ich spiele den Code wieder ein. Danach baue ich es um, so dass es die aktuelle passende REWRITE-Scheme nutzt.

**Comment by schuer** [comment]
Ich bin leider überhaupt nicht im Thema, was das AddOn eigentlich macht. Mich interessierte nur, warum es gelöscht werden sollte.

@skerbis Klingt gut. Wenn @joachimdoerr das als Lead für sinnvoll hält, fände ich das einen guten Move von dir! :) Aber wie gesagt: Ich bin nicht im Thema und wollte nur fragen, warum gelöscht werden soll.

**Comment by skerbis** [comment]
@joachimdoerr Was meinst du?

**Comment by hirbod** [comment]
Ich würde es Klasse finden, wenn das AddOn Möglichkeiten bieten würde, über eine Settingspage unterschiedliche Schemen zu aktivieren. In den Redaxo-Tricks haben wir ja schon ein paar angesammelt. Suffix an, Suffix aus, Präfix an, Präfix aus (oder Custom Zeug).

Weiterleiten in Child, Weiterleiten nur in Child wenn Parent kein Inhalt etc pp.

Kurzer Tip am Rande: beim Wechseln der Schemes muss die Pathlist gelöscht werden, sonst funzt es nicht.

**Comment by joachimdoerr** [comment]
ich fand die Lösung wie das Addon das Weiterleiten auf Kindkategorien handelt überholt. Damit FOR nicht mit allen Altlasten vollgestopft bleibt würde ich das Addon restlos entfernen wollen. Wenn natürlich @skerbis das Addon modernisieren will und es wie @Hirbod meint sogar noch aufpeppt mit coolen Funktionen ist das für mich gut. Nur find ich den status den wir jetzt aber nicht erhaltungswürdig.

**Comment by skerbis** [comment]
Ok. Ich fasse es an. Ich spiele jetzt erstmal die alte Version auf. Dann wird's umgebaut.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/schemes

**Comment by joachimdoerr** [comment]
Hast du jetzt 2 addons gebaut?

**Comment by skerbis** [comment]
ja. Das AddOn hier wird als veraltet markiert.
